
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/chase/.local/bin/"
      - "/home/chase/.local/share/nvim/mason/bin/"
      - "/home/chase/.config/hyde/scripts/"
      - "/home/chase/.local/lib/hyde/"
      - "/home/chase/.local/share/waybar/scripts/"
      - "/home/chase/.config/waybar/scripts/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
      - "/usr/lib/rustup/bin/"
      - "/var/lib/snapd/snap/bin/"
      - "/bin/"
    searched_directories:
      - "/home/chase/.local/bin/uname"
      - "/home/chase/.local/share/nvim/mason/bin/uname"
      - "/home/chase/.config/hyde/scripts/uname"
      - "/home/chase/.local/lib/hyde/uname"
      - "/home/chase/.local/share/waybar/scripts/uname"
      - "/home/chase/.config/waybar/scripts/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/chase/.local/bin"
        - "/home/chase/.local/share/nvim/mason/bin"
        - "/home/chase/.local/bin"
        - "/home/chase/.config/hyde/scripts"
        - "/home/chase/.local/lib/hyde"
        - "/home/chase/.local/share/waybar/scripts"
        - "/home/chase/.config/waybar/scripts"
        - "/home/chase/.config/hyde/scripts"
        - "/home/chase/.local/bin"
        - "/home/chase/.local/lib/hyde"
        - "/home/chase/.local/bin"
        - "/home/chase/.local/lib/hyde"
        - "/home/chase/.local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
        - "/usr/lib/rustup/bin"
        - "/var/lib/snapd/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.16.8-arch3-1 - x86_64
...
