#ifndef __VOLT_TOKEN_TYPE_H__
#define __VOLT_TOKEN_TYPE_H__

#ifdef __cplusplus
extern "C" {
#endif

typedef enum volt_token_type_t volt_token_type_t;
enum volt_token_type_t {
    // Single character
    VOLT_TOKEN_TYPE_NONE = 0,
    VOLT_TOKEN_TYPE_LPAREN,
    VOLT_TOKEN_TYPE_RPAREN,
    VOLT_TOKEN_TYPE_LBRACKET,
    VOLT_TOKEN_TYPE_RBRACKET,
    VOLT_TOKEN_TYPE_LBRACE,
    VOLT_TOKEN_TYPE_RBRACE,
    VOLT_TOKEN_TYPE_LANGLE,
    VOLT_TOKEN_TYPE_RANGLE,
    VOLT_TOKEN_TYPE_SINGLE_QUOTE,
    VOLT_TOKEN_TYPE_DOUBLE_QUOTE,
    VOLT_TOKEN_TYPE_SLASH,
    VOLT_TOKEN_TYPE_AMPERSAND,
    VOLT_TOKEN_TYPE_AT,
    VOLT_TOKEN_TYPE_BANG,
    VOLT_TOKEN_TYPE_PERCENT,
    VOLT_TOKEN_TYPE_CARET,  // ^
    VOLT_TOKEN_TYPE_STAR,
    VOLT_TOKEN_TYPE_UNDERSCORE,
    VOLT_TOKEN_TYPE_TACK,
    VOLT_TOKEN_TYPE_PLUS,
    VOLT_TOKEN_TYPE_EQUAL,
    VOLT_TOKEN_TYPE_BAR,  // |
    VOLT_TOKEN_TYPE_COLON,
    VOLT_TOKEN_TYPE_SEMICOLON,
    VOLT_TOKEN_TYPE_DOT,
    VOLT_TOKEN_TYPE_COMMA,
    VOLT_TOKEN_TYPE_QUESTION,  // ?

    // Double character
    VOLT_TOKEN_TYPE_EQUAL_EQUAL,
    VOLT_TOKEN_TYPE_BANG_EQUAL,
    VOLT_TOKEN_TYPE_AMPERSAND_EQUAL,
    VOLT_TOKEN_TYPE_BAR_EQUAL,
    VOLT_TOKEN_TYPE_PLUS_EQUAL,
    VOLT_TOKEN_TYPE_STAR_EQUAL,
    VOLT_TOKEN_TYPE_TACK_EQUAL,
    VOLT_TOKEN_TYPE_SLASH_EQAL,
    VOLT_TOKEN_TYPE_SLASH_SLASH,
    VOLT_TOKEN_TYPE_SLASH_STAR,
    VOLT_TOKEN_TYPE_STAR_SLASH,
    VOLT_TOKEN_TYPE_DOT_DOT,
    VOLT_TOKEN_TYPE_COLON_COLON,

    // Keywords
    VOLT_TOKEN_TYPE_I8,
    VOLT_TOKEN_TYPE_I16,
    VOLT_TOKEN_TYPE_I32,
    VOLT_TOKEN_TYPE_I64,
    VOLT_TOKEN_TYPE_I128,
    VOLT_TOKEN_TYPE_U8,
    VOLT_TOKEN_TYPE_U16,
    VOLT_TOKEN_TYPE_U32,
    VOLT_TOKEN_TYPE_U64,
    VOLT_TOKEN_TYPE_U128,
    VOLT_TOKEN_TYPE_F16,
    VOLT_TOKEN_TYPE_F32,
    VOLT_TOKEN_TYPE_F64,
    VOLT_TOKEN_TYPE_F128,
    VOLT_TOKEN_TYPE_BOOL,
    VOLT_TOKEN_TYPE_ISIZE,
    VOLT_TOKEN_TYPE_USIZE,
    VOLT_TOKEN_TYPE_CSTR,
    VOLT_TOKEN_TYPE_STR,
    VOLT_TOKEN_TYPE_CONST,
    VOLT_TOKEN_TYPE_VAR,
    VOLT_TOKEN_TYPE_LET,
    VOLT_TOKEN_TYPE_STATIC,
    VOLT_TOKEN_TYPE_ATTACH,
    VOLT_TOKEN_TYPE_STRUCT,
    VOLT_TOKEN_TYPE_ENUM,
    VOLT_TOKEN_TYPE_FN,
    VOLT_TOKEN_TYPE_ERROR,
    VOLT_TOKEN_TYPE_COMPTIME,
    VOLT_TOKEN_TYPE_CONSTRAINT,
    VOLT_TOKEN_TYPE_ASYNC,
    VOLT_TOKEN_TYPE_TRUE,
    VOLT_TOKEN_TYPE_FALSE,
    VOLT_TOKEN_TYPE_EXTERN,
    VOLT_TOKEN_TYPE_EXPORT,
    VOLT_TOKEN_TYPE_NAMESPACE,
    VOLT_TOKEN_TYPE_USE,
    VOLT_TOKEN_TYPE_THIS,
    VOLT_TOKEN_TYPE_MOVE,
    VOLT_TOKEN_TYPE_COPY,
    VOLT_TOKEN_TYPE_IF,
    VOLT_TOKEN_TYPE_ELSE,
    VOLT_TOKEN_TYPE_FOR,
    VOLT_TOKEN_TYPE_WHILE,
    VOLT_TOKEN_TYPE_LOOP,
    VOLT_TOKEN_TYPE_TRY,
    VOLT_TOKEN_TYPE_CATCH,
    VOLT_TOKEN_TYPE_NULL,
    VOLT_TOKEN_TYPE_SUSPEND,
    VOLT_TOKEN_TYPE_RESUME
};

#ifdef __cplusplus
}
#endif

#endif  // __VOLT_TOKEN_TYPE_H__
