#ifndef __VOLT_TOKEN_TYPE_H__
#define __VOLT_TOKEN_TYPE_H__

#ifdef __cplusplus
extern "C" {
#endif

typedef enum volt_token_type_t volt_token_type_t;
enum volt_token_type_t {
    // Single character
    VOLT_TOKEN_TYPE_NONE = 0,
    VOLT_TOKEN_TYPE_LPAREN,        // (
    VOLT_TOKEN_TYPE_RPAREN,        // )
    VOLT_TOKEN_TYPE_LBRACKET,      // [
    VOLT_TOKEN_TYPE_RBRACKET,      // ]
    VOLT_TOKEN_TYPE_LBRACE,        // {
    VOLT_TOKEN_TYPE_RBRACE,        // }
    VOLT_TOKEN_TYPE_LANGLE,        // <
    VOLT_TOKEN_TYPE_RANGLE,        // >
    VOLT_TOKEN_TYPE_SINGLE_QUOTE,  // '
    VOLT_TOKEN_TYPE_DOUBLE_QUOTE,  // "
    VOLT_TOKEN_TYPE_SLASH,         // /
    VOLT_TOKEN_TYPE_AMPERSAND,     // &
    VOLT_TOKEN_TYPE_AT,            // @
    VOLT_TOKEN_TYPE_BANG,          // !
    VOLT_TOKEN_TYPE_PERCENT,       // %
    VOLT_TOKEN_TYPE_CARET,         // ^
    VOLT_TOKEN_TYPE_TILDE,         // ~
    VOLT_TOKEN_TYPE_HASH,          // #
    VOLT_TOKEN_TYPE_STAR,          // *
    VOLT_TOKEN_TYPE_UNDERSCORE,    // _
    VOLT_TOKEN_TYPE_TACK,          // -
    VOLT_TOKEN_TYPE_PLUS,          // +
    VOLT_TOKEN_TYPE_EQUAL,         // =
    VOLT_TOKEN_TYPE_BAR,           // |
    VOLT_TOKEN_TYPE_COLON,         // :
    VOLT_TOKEN_TYPE_SEMICOLON,     // ;
    VOLT_TOKEN_TYPE_DOT,           // .
    VOLT_TOKEN_TYPE_COMMA,         // ,
    VOLT_TOKEN_TYPE_QUESTION,      // ?

    // Double character
    VOLT_TOKEN_TYPE_EQUAL_EQUAL,          // ==
    VOLT_TOKEN_TYPE_BANG_EQUAL,           // !=
    VOLT_TOKEN_TYPE_AMPERSAND_EQUAL,      // &=
    VOLT_TOKEN_TYPE_TILDE_EQUAL,          // ~=
    VOLT_TOKEN_TYPE_LANGLE_LANGLE,        // <<
    VOLT_TOKEN_TYPE_RANGLE_RANGLE,        // >>
    VOLT_TOKEN_TYPE_BAR_EQUAL,            // |=
    VOLT_TOKEN_TYPE_AMPERSAND_AMPERSAND,  // &&
    VOLT_TOKEN_TYPE_BAR_BAR,              // ||
    VOLT_TOKEN_TYPE_CARET_EQUAL,          // ^=
    VOLT_TOKEN_TYPE_LANGLE_EQUAL,         // <=
    VOLT_TOKEN_TYPE_RANGLE_EQUAL,         // >=
    VOLT_TOKEN_TYPE_PERCENT_EQUAL,        // %=
    VOLT_TOKEN_TYPE_EQUAL_RANGLE,         // =>
    VOLT_TOKEN_TYPE_PLUS_PLUS,            // ++
    VOLT_TOKEN_TYPE_TACK_TACK,            // --
    VOLT_TOKEN_TYPE_TACK_RANGLE,          // ->
    VOLT_TOKEN_TYPE_PLUS_EQUAL,           // +=
    VOLT_TOKEN_TYPE_STAR_EQUAL,           // *=
    VOLT_TOKEN_TYPE_TACK_EQUAL,           // -=
    VOLT_TOKEN_TYPE_SLASH_EQUAL,          // /=
    VOLT_TOKEN_TYPE_SLASH_SLASH,          // //
    VOLT_TOKEN_TYPE_SLASH_STAR,           // /*
    VOLT_TOKEN_TYPE_STAR_SLASH,           // */
    VOLT_TOKEN_TYPE_DOT_DOT,              // ..
    VOLT_TOKEN_TYPE_COLON_COLON,          // ::

    // Triple character
    VOLT_TOKEN_TYPE_DOT_DOT_EQUAL,        // ..=
    VOLT_TOKEN_TYPE_LANGLE_LANGLE_EQUAL,  // <<=
    VOLT_TOKEN_TYPE_RANGLE_RANGLE_EQUAL,  // >>=

    // Literalls
    VOLT_TOKEN_TYPE_NUMBER_LITERAL,      // 0->9 + '.' (float)
    VOLT_TOKEN_TYPE_STRING_LITERAL,      // "string" or 'c'
    VOLT_TOKEN_TYPE_IDENTIFIER_LITERAL,  // variable names, function names, etc.

    // Keywords
    VOLT_TOKEN_TYPE_I8_KW,
    VOLT_TOKEN_TYPE_I16_KW,
    VOLT_TOKEN_TYPE_I32_KW,
    VOLT_TOKEN_TYPE_I64_KW,
    VOLT_TOKEN_TYPE_I128_KW,
    VOLT_TOKEN_TYPE_U8_KW,
    VOLT_TOKEN_TYPE_U16_KW,
    VOLT_TOKEN_TYPE_U32_KW,
    VOLT_TOKEN_TYPE_U64_KW,
    VOLT_TOKEN_TYPE_U128_KW,
    VOLT_TOKEN_TYPE_F16_KW,
    VOLT_TOKEN_TYPE_F32_KW,
    VOLT_TOKEN_TYPE_F64_KW,
    VOLT_TOKEN_TYPE_F128_KW,
    VOLT_TOKEN_TYPE_BOOL_KW,
    VOLT_TOKEN_TYPE_ISIZE_KW,
    VOLT_TOKEN_TYPE_USIZE_KW,
    VOLT_TOKEN_TYPE_TYPE_KW,
    VOLT_TOKEN_TYPE_CSTR_KW,
    VOLT_TOKEN_TYPE_STR_KW,
    VOLT_TOKEN_TYPE_VAR_KW,
    VOLT_TOKEN_TYPE_VAL_KW,
    VOLT_TOKEN_TYPE_STATIC_KW,
    VOLT_TOKEN_TYPE_ATTACH_KW,
    VOLT_TOKEN_TYPE_STRUCT_KW,
    VOLT_TOKEN_TYPE_ENUM_KW,
    VOLT_TOKEN_TYPE_FN_KW,
    VOLT_TOKEN_TYPE_ERROR_KW,
    VOLT_TOKEN_TYPE_COMPTIME_KW,
    VOLT_TOKEN_TYPE_RETURN_KW,
    VOLT_TOKEN_TYPE_BREAK_KW,
    VOLT_TOKEN_TYPE_CONTINUE_KW,
    VOLT_TOKEN_TYPE_INTERNAL_KW,
    VOLT_TOKEN_TYPE_PUBLIC_KW,
    VOLT_TOKEN_TYPE_TRAIT_KW,
    VOLT_TOKEN_TYPE_ASYNC_KW,
    VOLT_TOKEN_TYPE_TRUE_KW,
    VOLT_TOKEN_TYPE_FALSE_KW,
    VOLT_TOKEN_TYPE_EXTERN_KW,
    VOLT_TOKEN_TYPE_EXPORT_KW,
    VOLT_TOKEN_TYPE_NAMESPACE_KW,
    VOLT_TOKEN_TYPE_USE_KW,
    VOLT_TOKEN_TYPE_THIS_KW,
    VOLT_TOKEN_TYPE_MOVE_KW,
    VOLT_TOKEN_TYPE_IN_KW,
    VOLT_TOKEN_TYPE_COPY_KW,
    VOLT_TOKEN_TYPE_IF_KW,
    VOLT_TOKEN_TYPE_ELSE_KW,
    VOLT_TOKEN_TYPE_FOR_KW,
    VOLT_TOKEN_TYPE_WHILE_KW,
    VOLT_TOKEN_TYPE_LOOP_KW,
    VOLT_TOKEN_TYPE_TRY_KW,
    VOLT_TOKEN_TYPE_CATCH_KW,
    VOLT_TOKEN_TYPE_NULL_KW,
    VOLT_TOKEN_TYPE_SUSPEND_KW,
    VOLT_TOKEN_TYPE_RESUME_KW,
    VOLT_TOKEN_TYPE_AS_KW,
    VOLT_TOKEN_TYPE_DEFER_KW
};

#ifdef __cplusplus
}
#endif

#endif  // __VOLT_TOKEN_TYPE_H__
